### ISSUE TITLE
Grunt?

### ISSUE THREAD

**Issue by kevinkashou** [emiloberg/markdown-styleguide-generator#3]
How would you set this up in grunt?

**Comment by emiloberg** [comment]
Hi!

See the last part of the README: https://github.com/emiloberg/markdown-styleguide-generator#run-with-gulpgrunt

The example in the README is with Gulp, but you can achieve the same thing with [grunt-shell](https://www.npmjs.com/package/grunt-shell).

Did that work out for you?

**Comment by kevinkashou** [comment]
Yah that works! :) Thanks
