### ISSUE TITLE
Having multiple code examples on the same chapter

### ISSUE THREAD

**Issue by luukhartsema** [emiloberg/markdown-styleguide-generator#7]
In the screenshot I noticed the pagination chapter in the styleguide contained two sections (Pagination and Pagination/alignment). I wonder what markup is needed to achieve this. 

Till now i've only been able to have one code example per chapter. Would appreciate your help. Thanks in advance.

**Comment by emiloberg** [comment]
Hi! 

Might not be totally clear in the README ([https://github.com/emiloberg/markdown-styleguide-generator#line-2](https://github.com/emiloberg/markdown-styleguide-generator#line-2)), but:

> Every style guide comment must have a heading. # is the Markdown syntax for a heading (equivalent to h1). The name of this section will be Glyphs (which will be shown in the menu). The subsection will be Style (which will be shown in the menu when it's expanded). The heading (the part before the slash) is required, the slash and the subsection is optional.

So what this means is that if you create the style guide section

```
# Pagination
```

and then create 

```
# Pagination/Sizes
```

They'll be on the same chapter.

Here's an example from the actual file the screenshot is created from:

``````
/* SG
# Pagination
* Use `.disabled` for unclickable links and `.active` to indicate the current page.

```
<div class="pagination">
  <ul>
    <li class="disabled"><a href="#">«</a></li>
    <li class="active"><a href="#">1</a></li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="#">5</a></li>
    <li><a href="#">»</a></li>
  </ul>
</div>
```
*/

/* SG
# Pagination/Alignment
* Add one of two optional classes to change the alignment of pagination links: `.pagination-centered` and `.pagination-right`.

```
<div class="pagination pagination-centered">
  <ul>
    <li class="disabled"><a href="#">«</a></li>
    <li class="active"><a href="#">1</a></li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="#">5</a></li>
    <li><a href="#">»</a></li>
  </ul>
</div>
```
*/
``````

**Comment by luukhartsema** [comment]
Thanks very clear now!
